### ISSUE TITLE
Support `import` function

### ISSUE THREAD

**Issue by jbrantly** [thgreasi/babel-plugin-system-import-transformer#11]
Apparently the module loader spec is now using `import()` for dynamic loading. Would be great if this plugin could support both syntaxes. Babel syntax plugin [here](http://babeljs.io/docs/plugins/syntax-dynamic-import/).

**Comment by thgreasi** [comment]
That's great!
I will start working on it as soon as I get some free time.
Thanks for reporting!

**Comment by thgreasi** [comment]
I just released v3.0.0 that adds support for the `import()` syntax.
I will probably also open a new issue for tracking support of `require.ensure`.
