### ISSUE TITLE
System is not defined

### ISSUE THREAD

**Issue by pptang** [thgreasi/babel-plugin-system-import-transformer#15]
After webpack 4, it seems System.import is deprecated, which results in this issue

**Comment by thgreasi** [comment]
Is this still an issue or you?
Any further details?
You can use the `import()` syntax which is also supported.
On the other hand, babel should have transformed your `System.import` calls before they reach webpack.

**Comment by pptang** [comment]
Sorry I mis-open the issue in this repo!
