### ISSUE TITLE
only client side?

### ISSUE THREAD

**Issue by mmahalwy** [thgreasi/babel-plugin-system-import-transformer#3]
Does this support server-side too?

**Comment by thgreasi** [comment]
I expect it to work wherever babel is used. If you use babel on your nodejs
scripts, probably configured for CommonJS, then it will replace
System.import() calls with promisefied require() calls. To be honest, for
nodejs scripts I would prefer using es6 imports.

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer

**Comment by thgreasi** [comment]
I will be more than happy to hear about your results/finding.
Feel free to re-open on just simply comment.

**Comment by mmahalwy** [comment]
ended up using the commonjs method and having it be pushed to my babel register. thanks!
