### ISSUE TITLE
Cannot transform when module name was a variant rather than literal

### ISSUE THREAD

**Issue by shaunxu** [thgreasi/babel-plugin-system-import-transformer#4]
This works.

``` js
System.import('./my-module').then((module) => {
    console.log(module);
}).catch((error) => {
    console.log(`Failed: ${error}`);
});
```

But if I put my module path into a variant it doesn't work.

``` js
const moduleName = './my-module';
System.import(moduleName).then((module) => {
    console.log(module);
}).catch((error) => {
    console.log(`Failed: ${error}`);
});
```

Seems that this plugin only transform `System.import` when the argument is literal. But I think in most cases, we use module loader when the module name was defined in a config file, or loop files in a folder.

**Comment by thgreasi** [comment]
This can't be done since in CommonJS `require('module')` can't accept a variant as a parameter. In more details, CommonJS needs string literals as argument to the `require()` method, so that it can statically analyze the source and generate bundle with all the required modules.

**Comment by thgreasi** [comment]
What module type are you targeting?

**Comment by shaunxu** [comment]
Yes I was using 'common'.

**Comment by thgreasi** [comment]
I this case (as said before) this can't be done since it is a limitation of

## the way that CommonJS bundlers work.

_Thodoris Greasidis_
Computer, Networking &
Communications Engineer
